import type { AppState, Thing } from "./domain";

const date = (day: string) => `2026-${day}T15:00:00-05:00`;

export const seedThings: Thing[] = [
  {
    id: "camping-red-oak",
    title: "Camping — Red Oak",
    summary: "A comfortable, elevated campsite for 15 people—with room for a cot, projector, and lighting that feels intentional.",
    ownerNextAction: "Jerry needs to approve the CORE tent purchase plan.",
    assistantNextAction: "Compare two quieter campsite lighting directions.",
    category: "Trips & Experiences",
    status: "Moving",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: true,
    archived: false,
    lastMoved: date("08-13"),
    location: "Red Oak, Illinois",
    dates: [
      { label: "Camping weekend", start: date("09-04"), end: date("09-07"), precision: "range", readiness: "Tent undecided · six open preparations", unresolved: 6 },
      { label: "Demo Yeti return window", start: date("09-14"), precision: "exact", readiness: "Demo data — confirm keep or return; no real order", unresolved: 1 },
    ],
    contacts: [{ id: "jordan", name: "Jordan", context: "Camping friend" }],
    options: [
      { id: "core-tent", name: "CORE 10-person cabin tent", description: "Tall cabin shape with room for the cot and projector setup.", price: "$349.99", source: "https://www.coreequipment.com/", recommendation: "Best fit for the group layout and easiest setup.", tradeoff: "Bulkier packed size than the alternatives.", status: "recommended" },
      { id: "snow-peak-chair", name: "Snow Peak Low Beach Chair", description: "Low-profile canvas chair with wood arms.", price: "$169", source: "https://www.snowpeak.com/", recommendation: "Cleanest look around the fire.", tradeoff: "Premium price for a camp chair.", status: "saved" },
      { id: "dji-power", name: "DJI Power 1000 V2", description: "Quiet portable power for the projector and campsite lighting.", source: "https://www.dji.com/", tradeoff: "Confirm actual power needs before buying.", status: "considering" },
    ],
    notes: [{ id: "camp-note-1", author: "Jerry", body: "Keep the setup intentional, not corny.", at: date("08-12") }],
    links: [],
    followUps: [],
    sections: [
      { id: "camp-explore", title: "Still to explore", body: "Tasteful exterior lighting, softer light inside the tent, and a small table beside the cot." },
      { id: "camp-owned", title: "Already owned", body: "Cot · projector · screen. Demo records only—no purchase is implied." },
      { id: "camp-demo-order", title: "Demo order — not live", body: "Yeti bottle · delivered demo state · return by Sep 14 · reference DEMO-YETI-001. This is fictional seed data, not a real purchase." },
    ],
  },
  {
    id: "oasis-paint-sip",
    title: "Oasis Paint & Sip",
    summary: "An ABBA-inspired night at Oasis Kitchen & Bar. The concept is set; instructor and supplies need final approval.",
    ownerNextAction: "Approve Vanessa for Sep 12 at $200.",
    assistantNextAction: "Prepare the supply plan after Jerry decides on Vanessa.",
    category: "Business",
    status: "Needs You",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-13"),
    waitingOn: "Jerry",
    location: "Oasis Kitchen & Bar · Lockport",
    dates: [{ label: "Paint & Sip", start: date("09-12"), precision: "exact", readiness: "Instructor awaiting approval", unresolved: 2 }],
    contacts: [
      { id: "vanessa", name: "Vanessa", context: "Painter / instructor", location: "Chicago", note: "Quoted $200; available for Sep 12." },
      { id: "adrian", name: "Adrian", context: "Venue owner", organization: "Oasis Kitchen & Bar", location: "Lockport" },
    ],
    options: [],
    notes: [],
    links: [],
    followUps: [{ id: "followup-adrian", waitingOn: "Adrian", date: date("08-15"), channel: "Draft message", note: "Confirm venue capacity before promotion begins.", state: "drafted" }],
    sections: [
      { id: "oasis-concept", title: "The concept", body: "Dancing Queen: an ABBA-inspired social painting night with warm lighting, a guided piece, and a short after-paint playlist." },
      { id: "oasis-economics", title: "Event shape", body: "Working capacity: 40 guests · ticket direction: $45 · instructor quote: $200 · venue and supply costs still need confirmation before any revenue projection is treated as real." },
      { id: "oasis-promotion", title: "Promotion direction", body: "Draft an ABBA-inspired visual and a short venue announcement after the instructor decision. No post or message has been sent." },
    ],
  },
  {
    id: "christmas-trip",
    title: "Family Christmas Trip 2026",
    summary: "A family holiday somewhere warm or culturally rich. Italy, Spain, and Costa Rica are the current shortlist.",
    ownerNextAction: "Review the destination shortlist and choose the trip energy.",
    assistantNextAction: "Compare flight windows for Italy and Costa Rica.",
    category: "Trips & Experiences",
    status: "Exploring",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-05"),
    dates: [{ label: "Possible family trip", start: "2026-12-01T12:00:00-06:00", precision: "month", readiness: "Destination shortlist in progress", unresolved: 4 }],
    contacts: [],
    options: [
      { id: "italy", name: "Italy", description: "Food, cities, and family-friendly rail travel.", recommendation: "Best all-around memory maker.", tradeoff: "Cooler weather and higher holiday pricing.", status: "recommended" },
      { id: "spain", name: "Spain", description: "Milder cities, great food, and strong value.", tradeoff: "Still a long travel day.", status: "considering" },
      { id: "costa-rica", name: "Costa Rica", description: "Warm weather, nature, and simpler outdoor days.", tradeoff: "Less city/culture than Europe.", status: "considering" },
    ],
    notes: [],
    links: [],
    followUps: [],
    sections: [{ id: "trip-question", title: "Decision to make", body: "Do we want warmth and ease, or a bigger cultural trip? Once that is clear, flight windows and neighborhoods can be compared." }],
  },
  {
    id: "fall-wardrobe",
    title: "Fall Wardrobe",
    summary: "Find better trousers and a few clean fall pieces—good fabric, quiet color, no loud logos or generic-looking products.",
    ownerNextAction: "Review Maria’s first trouser recommendation.",
    assistantNextAction: "Find two quieter trouser options with a clean drape.",
    category: "Shopping",
    status: "Exploring",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-11"),
    dates: [],
    contacts: [],
    options: [
      { id: "suitsupply", name: "SuitSupply wool trousers", description: "Clean drape, useful neutral, easy to dress up or down.", recommendation: "Best place to start.", tradeoff: "Needs an in-person fit check.", status: "recommended" },
      { id: "dark-denim", name: "Clean dark denim", description: "No distressing or loud hardware.", status: "saved" },
      { id: "olive-trouser", name: "Relaxed olive trouser", description: "More fashion-forward cut.", tradeoff: "Rejected as too loud.", status: "rejected" },
    ],
    notes: [],
    links: [],
    followUps: [],
    sections: [{ id: "wardrobe-fit", title: "Taste brief", body: "Simple silhouette, strong fabric, earthy or dark neutrals, minimal branding." }],
  },
  {
    id: "birthday",
    title: "Birthday",
    summary: "Plan something memorable without forcing a big production. The direction is still open.",
    ownerNextAction: "Choose: intimate dinner, one-night escape, or group night.",
    assistantNextAction: "Wait for Jerry’s direction before researching venues.",
    category: "Personal",
    status: "Needs You",
    permission: "YOU",
    keepMoving: false,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-09"),
    waitingOn: "Jerry",
    dates: [{ label: "Birthday", start: date("09-08"), precision: "exact", readiness: "No plan selected yet", unresolved: 3 }],
    contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "birthday-direction", title: "Smallest decision", body: "Choose the energy: intimate dinner, one-night escape, or a bigger group night." }],
  },
  {
    id: "dj-restart",
    title: "DJ Restart",
    summary: "Explore a low-pressure way to start making and sharing music again.",
    ownerNextAction: "Choose three records for a private 20-minute set.",
    assistantNextAction: "Surface one low-pressure setup idea when the timing feels right.",
    category: "Creative",
    status: "Someday",
    permission: "YOU",
    keepMoving: true,
    surpriseMe: true,
    archived: false,
    lastMoved: date("07-28"),
    dates: [], contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "dj-next", title: "A low-pressure next move", body: "Build one 20-minute set around three records you already love—nothing to publish yet." }],
  },
  {
    id: "chicago-date-nights",
    title: "Chicago Date Nights",
    summary: "Keep an eye out for interesting, non-generic date-night ideas around Chicago.",
    ownerNextAction: "Save or reject the next idea Maria surfaces.",
    assistantNextAction: "Find one design-forward Chicago date idea under $200.",
    category: "Future",
    status: "Someday",
    permission: "GO",
    keepMoving: false,
    surpriseMe: true,
    archived: false,
    lastMoved: date("08-01"),
    location: "Chicago",
    dates: [], contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "date-taste", title: "What fits", body: "Good design, food or music with a point of view, and enough room to actually talk." }],
  },
  {
    id: "summer-house-party",
    title: "Summer House Party",
    summary: "A finished backyard evening with a vinyl set, low lighting, and family-style food.",
    ownerNextAction: "No next move — this memory is complete.",
    assistantNextAction: "No next move — this memory is complete.",
    category: "Personal",
    status: "Done",
    permission: "GO",
    keepMoving: false,
    surpriseMe: false,
    archived: true,
    lastMoved: date("07-18"),
    dates: [], contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "party-memory", title: "What worked", body: "The smaller guest list and family-style table made the night feel easy. Keep that format." }],
  },
];

export const initialState: AppState = {
  schemaVersion: 2,
  things: seedThings,
  approvals: [
    { id: "approve-vanessa", thingId: "oasis-paint-sip", title: "Approve Vanessa for the Paint & Sip", context: "Vanessa can lead the event for $200 and is available Sep 12.", recommendation: "Approve her—she has the right group experience and fits the budget.", whyNow: "The event is one month out and supplies depend on the instructor plan.", actionLabel: "Approve $200", meta: "$200 · Sep 12 · Vanessa", status: "pending" },
    { id: "approve-tent", thingId: "camping-red-oak", title: "Choose the main tent", context: "The CORE 10-person cabin tent fits the cot, projector setup, and two sleepers.", recommendation: "Buy the CORE tent if the packed size works for the car.", whyNow: "Camping is approaching and the rest of the layout depends on it.", actionLabel: "Approve purchase plan", meta: "$349.99 · Purchase not placed", status: "pending" },
    { id: "approve-trip", thingId: "christmas-trip", title: "Review the destination shortlist", context: "Italy, Spain, and Costa Rica are the three strongest directions.", recommendation: "Start with Italy; keep Costa Rica as the warmer backup.", whyNow: "Holiday flight windows are worth narrowing before prices tighten.", actionLabel: "Review shortlist", meta: "3 destinations · December 2026", status: "pending" },
    { id: "approve-birthday", thingId: "birthday", title: "Choose the birthday energy", context: "The useful decision is intimate dinner, one-night escape, or bigger group night.", recommendation: "Pick the feeling first; planning can stay light after that.", whyNow: "A direction unlocks every other detail.", actionLabel: "Choose direction", meta: "Owner-only · Sep 8", status: "pending" },
  ],
  activities: [
    { id: "activity-1", thingId: "camping-red-oak", actor: "Maria", text: "Maria compared the CORE 10-person tent with two alternatives.", at: date("08-13") },
    { id: "activity-2", thingId: "oasis-paint-sip", actor: "Maria", text: "Vanessa confirmed availability for Sep 12.", at: date("08-13") },
    { id: "activity-3", thingId: "fall-wardrobe", actor: "Maria", text: "Maria narrowed the trouser search to three quieter options.", at: date("08-12") },
    { id: "activity-4", thingId: "camping-red-oak", actor: "Jerry", text: "Jerry saved the Snow Peak chair for later.", at: date("08-12") },
    { id: "activity-5", thingId: "oasis-paint-sip", actor: "Maria", text: "Maria drafted a follow-up for Adrian.", at: date("08-11") },
  ],
  inbox: [
    { id: "inbox-1", type: "voice", raw: "For camping maybe we need tasteful lights around the tent, something inside, and a small table next to the cot. I don’t want it looking corny.", status: "needs_review", createdAt: date("08-13"), proposal: { title: "Camping — Red Oak", summary: "Explore exterior and interior lighting plus a small cot-side table; keep the campsite tasteful.", category: "Trips & Experiences", status: "Moving", permission: "GO", relatedThingId: "camping-red-oak", extracted: ["Exterior ambient lighting", "Interior tent lighting", "Small cot-side table", "Constraint: intentional, not corny"], confidence: "High confidence" } },
    { id: "inbox-2", type: "link", raw: "https://example.com/wisconsin-cabin — might be fire for fall. Look into it whenever.", status: "needs_review", createdAt: date("08-12"), proposal: { title: "Wisconsin Cabin Weekend", summary: "Look into a possible cabin weekend in Wisconsin this fall.", category: "Trips & Experiences", status: "Someday", permission: "GO", extracted: ["Location: Wisconsin", "Timing: fall, date uncertain", "Intent: explore a cabin weekend"], confidence: "Please check" } },
  ],
};
