import type { AppState, Thing, ThingItem, ThingSection } from "./domain";

const date = (day: string) => `2026-${day}T15:00:00-05:00`;

type SeedThing = Omit<Thing, "items" | "customFields" | "sections"> & {
  sections: Array<Omit<ThingSection, "position">>;
};

const baseThings: SeedThing[] = [
  {
    id: "camping-red-oak",
    title: "Camping — Red Oak",
    summary: "A comfortable, elevated campsite for 15 people—with room for a cot, projector, and lighting that feels intentional.",
    ownerNextAction: "Jerry needs to approve the CORE tent purchase plan.",
    assistantNextAction: "Compare two quieter campsite lighting directions.",
    category: "Trips & Experiences",
    status: "Moving",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: true,
    archived: false,
    lastMoved: date("08-13"),
    location: "Red Oak, Illinois",
    dates: [
      { label: "Camping weekend", start: date("09-04"), end: date("09-07"), precision: "range", readiness: "Tent undecided · six open preparations", unresolved: 6 },
      { label: "Demo Yeti return window", start: date("09-14"), precision: "exact", readiness: "Demo data — confirm keep or return; no real order", unresolved: 1 },
    ],
    contacts: [{ id: "jordan", name: "Jordan", context: "Camping friend" }],
    options: [
      { id: "core-tent", itemId: "camp-core-tent", name: "CORE 10-person cabin tent", description: "Tall cabin shape with room for the cot and projector setup.", price: "$349.99", source: "https://www.coreequipment.com/", recommendation: "Best fit for the group layout and easiest setup.", tradeoff: "Bulkier packed size than the alternatives.", status: "recommended" },
      { id: "snow-peak-chair", itemId: "camp-chair", name: "Snow Peak Low Beach Chair", description: "Low-profile canvas chair with wood arms.", price: "$169", source: "https://www.snowpeak.com/", recommendation: "Cleanest look around the fire.", tradeoff: "Premium price for a camp chair.", status: "saved" },
      { id: "dji-power", itemId: "camp-dji-power", name: "DJI Power 1000 V2", description: "Quiet portable power for the projector and campsite lighting.", source: "https://www.dji.com/", tradeoff: "Confirm actual power needs before buying.", status: "approved" },
      { id: "snow-peak-hozuki", itemId: "camp-exterior-lighting", name: "Snow Peak Hozuki", description: "A warm, dimmable lantern that suits the quieter campsite setup.", price: "$120", source: "https://www.snowpeak.com/", retailer: "Snow Peak", recommendation: "Best-looking choice. More expensive, but it fits the setup.", tradeoff: "$40 more than the BioLite.", status: "recommended" },
      { id: "biolite-alpenglow", itemId: "camp-exterior-lighting", name: "BioLite AlpenGlow 500", description: "Bright, rechargeable campsite light with a warm mode.", price: "$80", source: "https://www.bioliteenergy.com/", retailer: "BioLite", recommendation: "Better value and still clean-looking.", tradeoff: "More technical-looking than the Hozuki.", status: "considering" },
    ],
    notes: [{ id: "camp-note-1", author: "Jerry", body: "Keep the setup intentional, not corny.", at: date("08-12") }],
    links: [
      { id: "camp-link-core", itemId: "camp-core-tent", title: "CORE Equipment", url: "https://www.coreequipment.com/" },
      { id: "camp-link-rei", itemId: "camp-exterior-lighting", title: "REI lighting", url: "https://www.rei.com/c/camp-lighting" },
    ],
    followUps: [],
    sections: [
      { id: "camp-tent", title: "Tent setup", body: "" },
      { id: "camp-power", title: "Power", body: "" },
      { id: "camp-entertainment", title: "Entertainment", body: "Projector and screen are already owned." },
      { id: "camp-food", title: "Food & drinks", body: "" },
      { id: "camp-clothes", title: "Clothes & personal", body: "" },
      { id: "camp-ideas", title: "Ideas", body: "" },
    ],
  },
  {
    id: "find-a-tailor",
    title: "Find a tailor",
    summary: "Find a strong tailor for SuitSupply trousers and jackets—good enough for nicer clothes, not just basic hemming.",
    ownerNextAction: "Review Maria’s shortlist and decide who to call back.",
    assistantNextAction: "Follow up with Arthur and Lucca for pricing and turnaround.",
    category: "Personal",
    status: "Moving",
    permission: "GO",
    keepMoving: true,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-14"),
    location: "Chicago area",
    dates: [],
    contacts: [],
    options: [],
    notes: [{ id: "tailor-note-jerry", author: "Jerry", body: "Needs to be good enough for nicer clothes, not just basic hemming.", at: date("08-13") }],
    links: [
      { id: "arthur-web", itemId: "tailor-arthur", title: "Website", url: "https://arthurandlucca.com/" },
      { id: "arthur-maps", itemId: "tailor-arthur", title: "Google Maps", url: "https://maps.google.com/?q=Arthur+and+Lucca+Oak+Brook" },
      { id: "arthur-instagram", itemId: "tailor-arthur", title: "Instagram", url: "https://www.instagram.com/arthurandlucca/" },
    ],
    followUps: [{ id: "tailor-pricing", waitingOn: "Arthur and Lucca", date: date("08-16"), channel: "Call", note: "Ask about jacket sleeves and turnaround.", state: "drafted" }],
    waitingOn: "Arthur and Lucca",
    sections: [
      { id: "tailor-shortlist", title: "Shortlist", body: "" },
      { id: "tailor-questions", title: "Questions to ask", body: "" },
      { id: "tailor-notes", title: "Notes", body: "" },
    ],
  },
  {
    id: "oasis-paint-sip",
    title: "Mamma Mia — Dancing Queen",
    summary: "An ABBA-inspired night at Oasis Kitchen & Bar. The concept is set; instructor and supplies need final approval.",
    ownerNextAction: "Approve Vanessa for Sep 12 at $200.",
    assistantNextAction: "Prepare the supply plan after Jerry decides on Vanessa.",
    category: "Business",
    status: "Moving",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-13"),
    waitingOn: "Jerry",
    location: "Oasis Kitchen & Bar · Lockport",
    dates: [{ label: "Paint & Sip", start: date("09-12"), precision: "exact", readiness: "Instructor awaiting approval", unresolved: 2 }],
    contacts: [
      { id: "vanessa", name: "Vanessa", context: "Painter / instructor", location: "Chicago", note: "Quoted $200; available for Sep 12." },
      { id: "adrian", name: "Adrian", context: "Venue owner", organization: "Oasis Kitchen & Bar", location: "Lockport" },
    ],
    options: [],
    notes: [],
    links: [],
    followUps: [{ id: "followup-adrian", waitingOn: "Adrian", date: date("08-15"), channel: "Draft message", note: "Confirm venue capacity before promotion begins.", state: "drafted" }],
    sections: [
      { id: "oasis-concept", title: "Concept", body: "Dancing Queen: an ABBA-inspired social painting night with warm lighting, a guided piece, and a short after-paint playlist." },
      { id: "oasis-vendors", title: "Vendors", body: "Vanessa is the leading instructor at a quoted $200." },
      { id: "oasis-promotion", title: "Promotion", body: "Draft an ABBA-inspired visual and venue announcement. Nothing has been posted." },
      { id: "oasis-budget", title: "Budget", body: "Working capacity: 60 · ticket direction: $40 · venue and supply costs remain unconfirmed." },
      { id: "oasis-operations", title: "Operations", body: "Confirm materials, room layout, timing, and check-in." },
      { id: "oasis-adrian", title: "Needs Adrian", body: "Confirm venue capacity and operational constraints." },
      { id: "oasis-jerry", title: "Needs Jerry", body: "Approve Vanessa and the initial event direction." },
    ],
  },
  {
    id: "christmas-trip",
    title: "Family Christmas Trip 2026",
    summary: "A family holiday somewhere warm or culturally rich. Italy, Spain, and Costa Rica are the current shortlist.",
    ownerNextAction: "Review the destination shortlist and choose the trip energy.",
    assistantNextAction: "Compare flight windows for Italy and Costa Rica.",
    category: "Trips & Experiences",
    status: "Exploring",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-05"),
    dates: [{ label: "Possible family trip", start: "2026-12-01T12:00:00-06:00", precision: "month", readiness: "Destination shortlist in progress", unresolved: 4 }],
    contacts: [],
    options: [
      { id: "italy", itemId: "trip-shortlist", name: "Italy", description: "Food, cities, and family-friendly rail travel.", recommendation: "Best all-around memory maker.", tradeoff: "Cooler weather and higher holiday pricing.", status: "recommended" },
      { id: "spain", itemId: "trip-shortlist", name: "Spain", description: "Milder cities, great food, and strong value.", tradeoff: "Still a long travel day.", status: "considering" },
      { id: "costa-rica", itemId: "trip-shortlist", name: "Costa Rica", description: "Warm weather, nature, and simpler outdoor days.", tradeoff: "Less city/culture than Europe.", status: "considering" },
    ],
    notes: [],
    links: [],
    followUps: [],
    sections: [{ id: "trip-question", title: "Decision to make", body: "Do we want warmth and ease, or a bigger cultural trip? Once that is clear, flight windows and neighborhoods can be compared." }],
  },
  {
    id: "fall-wardrobe",
    title: "Fall Wardrobe",
    summary: "Find better trousers and a few clean fall pieces—good fabric, quiet color, no loud logos or generic-looking products.",
    ownerNextAction: "Review Maria’s first trouser recommendation.",
    assistantNextAction: "Find two quieter trouser options with a clean drape.",
    category: "Shopping",
    status: "Exploring",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-11"),
    dates: [],
    contacts: [],
    options: [
      { id: "suitsupply", itemId: "wardrobe-trousers", name: "SuitSupply wool trousers", description: "Clean drape, useful neutral, easy to dress up or down.", recommendation: "Best place to start.", tradeoff: "Needs an in-person fit check.", status: "recommended" },
      { id: "dark-denim", itemId: "wardrobe-trousers", name: "Clean dark denim", description: "No distressing or loud hardware.", status: "saved" },
      { id: "olive-trouser", itemId: "wardrobe-trousers", name: "Relaxed olive trouser", description: "More fashion-forward cut.", tradeoff: "Rejected as too loud.", status: "rejected" },
    ],
    notes: [],
    links: [],
    followUps: [],
    sections: [{ id: "wardrobe-fit", title: "Taste brief", body: "Simple silhouette, strong fabric, earthy or dark neutrals, minimal branding." }],
  },
  {
    id: "birthday",
    title: "Birthday",
    summary: "Plan something memorable without forcing a big production. The direction is still open.",
    ownerNextAction: "Choose: intimate dinner, one-night escape, or group night.",
    assistantNextAction: "Wait for Jerry’s direction before researching venues.",
    category: "Personal",
    status: "Needs You",
    permission: "YOU",
    keepMoving: false,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-09"),
    waitingOn: "Jerry",
    dates: [{ label: "Birthday", start: date("09-08"), precision: "exact", readiness: "No plan selected yet", unresolved: 3 }],
    contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "birthday-direction", title: "Smallest decision", body: "Choose the energy: intimate dinner, one-night escape, or a bigger group night." }],
  },
  {
    id: "dj-restart",
    title: "DJ Restart",
    summary: "Explore a low-pressure way to start making and sharing music again.",
    ownerNextAction: "Choose three records for a private 20-minute set.",
    assistantNextAction: "Surface one low-pressure setup idea when the timing feels right.",
    category: "Creative",
    status: "Someday",
    permission: "YOU",
    keepMoving: true,
    surpriseMe: true,
    archived: false,
    lastMoved: date("07-28"),
    dates: [], contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "dj-next", title: "A low-pressure next move", body: "Build one 20-minute set around three records you already love—nothing to publish yet." }],
  },
  {
    id: "chicago-date-nights",
    title: "Chicago Date Nights",
    summary: "Keep an eye out for interesting, non-generic date-night ideas around Chicago.",
    ownerNextAction: "Save or reject the next idea Maria surfaces.",
    assistantNextAction: "Find one design-forward Chicago date idea under $200.",
    category: "Future",
    status: "Someday",
    permission: "GO",
    keepMoving: false,
    surpriseMe: true,
    archived: false,
    lastMoved: date("08-01"),
    location: "Chicago",
    dates: [], contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "date-taste", title: "What fits", body: "Good design, food or music with a point of view, and enough room to actually talk." }],
  },
  {
    id: "summer-house-party",
    title: "Summer House Party",
    summary: "A finished backyard evening with a vinyl set, low lighting, and family-style food.",
    ownerNextAction: "No next move — this memory is complete.",
    assistantNextAction: "No next move — this memory is complete.",
    category: "Personal",
    status: "Done",
    permission: "GO",
    keepMoving: false,
    surpriseMe: false,
    archived: true,
    lastMoved: date("07-18"),
    dates: [], contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "party-memory", title: "What worked", body: "The smaller guest list and family-style table made the night feel easy. Keep that format." }],
  },
];

const item = (id: string, sectionId: string, title: string, position: number, extras: Partial<ThingItem> = {}): ThingItem => ({
  id, sectionId, title, position, type: "checklist", status: "open", links: [], notes: [], ...extras,
});

const planItems: Record<string, ThingItem[]> = {
  "camping-red-oak": [
    item("camp-core-tent", "camp-tent", "CORE 10-person cabin tent", 0, { type: "product", status: "complete", body: "Cabin height with space for the cot and projector setup." }),
    item("camp-cot", "camp-tent", "Standing cot", 1, { status: "complete" }),
    item("camp-bedding", "camp-tent", "Bedding", 2),
    item("camp-rug", "camp-tent", "Tent rug", 3),
    item("camp-bedside", "camp-tent", "Small bedside table", 4),
    item("camp-shoe-table", "camp-tent", "Shoe table", 5),
    item("camp-interior-lighting", "camp-tent", "Interior lighting", 6),
    item("camp-exterior-lighting", "camp-tent", "Exterior lighting", 7, { type: "product", recentSummary: "Maria added 2 options · 1h", needsYou: true, primaryAction: "Choose lighting", recommendation: "Snow Peak is the best-looking option; BioLite is the better value.", notes: [{ id: "light-note-maria", author: "Maria", body: "Could use one inside and one under the canopy.", at: date("08-14") }, { id: "light-note-jerry", author: "Jerry", body: "I like the Snow Peak more.", at: date("08-14") }] }),
    item("camp-dji-power", "camp-power", "DJI Power 1000 V2", 0, { type: "product", status: "complete", body: "Quiet power for the projector and campsite lighting." }),
    item("camp-extension", "camp-power", "Extension cord", 1),
    item("camp-usbc", "camp-power", "USB-C cables", 2),
    item("camp-power-strip", "camp-power", "Power strip", 3),
    item("camp-projector", "camp-entertainment", "Projector", 0, { status: "complete" }),
    item("camp-screen", "camp-entertainment", "130\" screen", 1, { status: "complete" }),
    item("camp-switch", "camp-entertainment", "Nintendo Switch", 2, { status: "complete" }),
    item("camp-hdmi", "camp-entertainment", "HDMI adapter", 3),
    item("camp-jbl", "camp-entertainment", "JBL PartyBox", 4, { status: "complete" }),
    item("camp-arrachera", "camp-food", "Arrachera", 0),
    item("camp-eggs", "camp-food", "Eggs", 1),
    item("camp-coffee", "camp-food", "Coffee", 2),
    item("camp-water", "camp-food", "Water", 3),
    item("camp-snacks", "camp-food", "Snacks", 4),
    item("camp-shoes", "camp-clothes", "Camp shoes", 0),
    item("camp-hiking-outfit", "camp-clothes", "Hiking outfit", 1),
    item("camp-rain", "camp-clothes", "Rain layer", 2),
    item("camp-toiletries", "camp-clothes", "Toiletries", 3),
    item("camp-front-rug", "camp-ideas", "Little rug in front of tent", 0, { type: "idea" }),
    item("camp-lantern", "camp-ideas", "Small lantern outside", 1, { type: "idea" }),
    item("camp-tray", "camp-ideas", "Folding tray / table", 2, { type: "idea" }),
    item("camp-chair", "camp-ideas", "Camp chair", 3, { type: "product", body: "One comfortable chair for the fire." }),
  ],
  "find-a-tailor": [
    item("tailor-arthur", "tailor-shortlist", "Arthur and Lucca", 0, { type: "place", location: "Oak Brook", body: "Maria’s top pick · Contacted today", recentSummary: "Maria called today", primaryAction: "Follow up", recommendation: "Best combination of quality and convenience.", notes: [{ id: "arthur-note-1", author: "Maria", body: "Strong menswear focus. Ask about jacket sleeve alterations and verify turnaround.", at: date("08-14") }] }),
    item("tailor-richard", "tailor-shortlist", "Richard Bennett Custom Tailors", 1, { type: "place", location: "Chicago", body: "Strongest for complicated jacket work." }),
    item("tailor-uncommon", "tailor-shortlist", "Uncommon Closet", 2, { type: "place", location: "Chicago", body: "Good alterations reputation." }),
    item("tailor-taper", "tailor-questions", "Trouser tapering", 0),
    item("tailor-sleeves", "tailor-questions", "Jacket sleeve shortening", 1),
    item("tailor-turnaround", "tailor-questions", "Turnaround time", 2),
    item("tailor-pricing", "tailor-questions", "Pricing", 3),
    item("tailor-rush", "tailor-questions", "Rush availability", 4),
    item("tailor-general-note", "tailor-notes", "Quality bar", 0, { type: "note", body: "Good enough for nicer clothes, not only basic hemming." }),
  ],
  "oasis-paint-sip": [
    item("oasis-concept-item", "oasis-concept", "Dancing Queen creative direction", 0, { type: "idea", status: "complete", body: "ABBA-inspired social painting night with warm lighting." }),
    item("oasis-vanessa", "oasis-vendors", "Vanessa · painting instructor", 0, { type: "person", body: "$200 · available Sep 12", needsYou: true, primaryAction: "Approve Vanessa" }),
    item("oasis-promo-art", "oasis-promotion", "Draft event artwork", 0),
    item("oasis-capacity-item", "oasis-operations", "Confirm venue capacity", 0, { body: "Waiting on Adrian" }),
  ],
  "christmas-trip": [item("trip-shortlist", "trip-question", "Destination shortlist", 0, { type: "place", body: "Italy · Spain · Costa Rica", needsYou: true, primaryAction: "Choose direction" })],
  "fall-wardrobe": [item("wardrobe-trousers", "wardrobe-fit", "Trouser shortlist", 0, { type: "product", body: "3 quieter options with a clean drape", recentSummary: "Maria added 3 options · yesterday" })],
};

export const seedThings: Thing[] = baseThings.map((thing) => ({
  ...thing,
  owner: thing.owner ?? "Jerry",
  priority: thing.priority ?? "normal",
  tags: thing.tags ?? [],
  relatedThingIds: thing.relatedThingIds ?? [],
  collaborators: thing.collaborators ?? ["Maria"],
  sections: thing.sections.map((section, position) => ({ ...section, position })),
  items: planItems[thing.id] ?? [],
  customFields: (thing.id === "oasis-paint-sip" ? [
    { id: "oasis-capacity", key: "capacity", label: "Capacity", type: "number", value: 60, position: 0 },
    { id: "oasis-ticket", key: "ticket_price", label: "Ticket Price", type: "currency", value: 40, position: 1 },
    { id: "oasis-instructor", key: "instructor", label: "Instructor", type: "contact", value: "Vanessa", position: 2 },
    { id: "oasis-venue", key: "venue", label: "Venue", type: "short_text", value: "Oasis Kitchen & Bar", position: 3 },
  ] : []) as Thing["customFields"],
})).concat({
  id: "camping-tent-setup", title: "Tent Setup", subtitle: "Subthing of Camping — Red Oak", description: "The physical sleep and shelter setup, separated so it can move independently.", summary: "Build a comfortable, intentional tent interior around the CORE cabin tent.", ownerNextAction: "Approve the main tent plan.", assistantNextAction: "Turn the selected gear into a setup checklist.", category: "Trips & Experiences", status: "Moving", permission: "APPROVE", keepMoving: true, surpriseMe: false, archived: false, lastMoved: date("08-13"), owner: "Jerry", collaborators: ["Maria"], priority: "high", tags: ["camping", "setup"], parentId: "camping-red-oak", relatedThingIds: [], dates: [], contacts: [], options: [], notes: [], links: [], followUps: [], sections: [{ id: "tent-layout", title: "Layout", body: "Cot, bedside table, shoe storage, rug, and clear walking space.", position: 0 }, { id: "tent-lighting", title: "Lighting", body: "Warm, low-output lighting inside and around the entrance.", position: 1 }], items: [], customFields: [],
});

export const initialState: AppState = {
  schemaVersion: 3,
  revision: 1,
  things: seedThings,
  approvals: [
    { id: "approve-vanessa", thingId: "oasis-paint-sip", title: "Approve Vanessa for the Paint & Sip", context: "Vanessa can lead the event for $200 and is available Sep 12.", recommendation: "Approve her—she has the right group experience and fits the budget.", whyNow: "The event is one month out and supplies depend on the instructor plan.", actionLabel: "Approve $200", meta: "$200 · Sep 12 · Vanessa", status: "pending" },
    { id: "approve-tent", thingId: "camping-red-oak", title: "Choose exterior lighting", context: "Snow Peak is nicer but $40 more. Which one fits the setup?", recommendation: "Choose Snow Peak Hozuki for the warmer, quieter look.", whyNow: "Lighting is the last visual choice before the tent setup is ready.", actionLabel: "Choose Snow Peak", meta: "$120 · Purchase not placed", status: "pending", amount: 120, currency: "USD", urgency: "normal", options: [{ id: "light-approve", label: "Choose Snow Peak", description: "Best-looking fit for the campsite." }, { id: "light-value", label: "Choose BioLite", description: "Better value at $80." }, { id: "light-keep-looking", label: "Keep looking" }], responses: [] },
    { id: "approve-trip", thingId: "christmas-trip", title: "Review the destination shortlist", context: "Italy, Spain, and Costa Rica are the three strongest directions.", recommendation: "Start with Italy; keep Costa Rica as the warmer backup.", whyNow: "Holiday flight windows are worth narrowing before prices tighten.", actionLabel: "Review shortlist", meta: "3 destinations · December 2026", status: "pending" },
    { id: "approve-birthday", thingId: "birthday", title: "Choose the birthday energy", context: "The useful decision is intimate dinner, one-night escape, or bigger group night.", recommendation: "Pick the feeling first; planning can stay light after that.", whyNow: "A direction unlocks every other detail.", actionLabel: "Choose direction", meta: "Owner-only · Sep 8", status: "pending" },
  ],
  activities: [
    { id: "activity-lighting", thingId: "camping-red-oak", actor: "Maria", text: "Maria added 2 lighting options.", at: date("08-14"), action: "product.created", entityType: "item", entityId: "camp-exterior-lighting" },
    { id: "activity-tailor", thingId: "find-a-tailor", actor: "Maria", text: "Maria added Arthur and Lucca to the shortlist.", at: date("08-14"), action: "item.created", entityType: "item", entityId: "tailor-arthur" },
    { id: "activity-1", thingId: "camping-red-oak", actor: "Maria", text: "Maria compared the CORE tent with two alternatives.", at: date("08-13") },
    { id: "activity-2", thingId: "oasis-paint-sip", actor: "Maria", text: "Vanessa confirmed availability for Sep 12.", at: date("08-13") },
    { id: "activity-3", thingId: "fall-wardrobe", actor: "Maria", text: "Maria narrowed the trouser search to three quieter options.", at: date("08-12") },
    { id: "activity-4", thingId: "camping-red-oak", actor: "Jerry", text: "Jerry saved the Snow Peak chair for later.", at: date("08-12") },
    { id: "activity-5", thingId: "oasis-paint-sip", actor: "Maria", text: "Maria drafted a follow-up for Adrian.", at: date("08-11") },
  ],
  inbox: [
    { id: "inbox-1", type: "voice", raw: "For camping maybe we need tasteful lights around the tent, something inside, and a small table next to the cot. I don’t want it looking corny.", status: "attached", createdAt: date("08-13"), proposal: { title: "Camping — Red Oak", summary: "Explore exterior and interior lighting plus a small cot-side table; keep the campsite tasteful.", category: "Trips & Experiences", status: "Moving", permission: "GO", relatedThingId: "camping-red-oak", extracted: ["Exterior ambient lighting", "Interior tent lighting", "Small cot-side table", "Constraint: intentional, not corny"], confidence: "High confidence" } },
    { id: "inbox-2", type: "link", raw: "https://example.com/wisconsin-cabin — might be fire for fall. Look into it whenever.", status: "needs_review", createdAt: date("08-12"), proposal: { title: "Wisconsin Cabin Weekend", summary: "Look into a possible cabin weekend in Wisconsin this fall.", category: "Trips & Experiences", status: "Someday", permission: "GO", extracted: ["Location: Wisconsin", "Timing: fall, date uncertain", "Intent: explore a cabin weekend"], confidence: "Please check" } },
  ],
  contacts: [
    { id: "vanessa", name: "Vanessa", context: "Artist / Painting Instructor", organization: "Independent", location: "Chicago", note: "Art degree · teaches kids · quoted $200", tags: ["vendor", "artist"] },
    { id: "adrian", name: "Adrian", context: "Owner", organization: "Oasis Kitchen & Bar", location: "Lockport", tags: ["venue", "restaurant"] },
    { id: "jordan", name: "Jordan", context: "Camping friend", tags: ["friend", "camping"] },
  ],
  preferences: [
    { id: "pref-camp-aesthetic", domain: "camping gear", attribute: "aesthetic", statement: "Avoid cheap or corny campsite styling.", sentiment: "dislikes", sourceType: "confirmed note", sourceId: "camp-note-1", confidence: 1, confirmed: true, createdAt: date("08-12") },
  ],
  templates: [
    { id: "template-blank", name: "Blank", description: "Start with an open brief.", type: "blank", sections: [], fields: [] },
    { id: "template-trip", name: "Trip", description: "Destinations, travel, stays, people, and budget.", type: "trip", sections: [{ title: "Destinations" }, { title: "Travel" }, { title: "Stays" }, { title: "People" }, { title: "Budget" }, { title: "Need Decision" }], fields: [{ label: "Budget", type: "currency" }, { label: "Travelers", type: "number" }] },
    { id: "template-event", name: "Event", description: "Concept, vendors, promotion, budget, and operations.", type: "event", sections: [{ title: "Concept" }, { title: "Vendors" }, { title: "Promotion" }, { title: "Budget" }, { title: "Operations" }], fields: [{ label: "Capacity", type: "number" }, { label: "Ticket Price", type: "currency" }] },
    { id: "template-shopping", name: "Shopping Project", description: "Research, shortlist, saved, bought, and rejected.", type: "shopping", sections: [{ title: "Research" }, { title: "Shortlist" }, { title: "Saved" }, { title: "Bought" }, { title: "Rejected" }], fields: [{ label: "Budget", type: "currency" }] },
    { id: "template-personal", name: "Personal Admin", description: "Context, next actions, documents, and follow-up.", type: "personal_admin", sections: [{ title: "Context" }, { title: "Next Actions" }, { title: "Documents" }, { title: "Follow-up" }], fields: [] },
    { id: "template-business", name: "Business Initiative", description: "Goals, workstreams, people, budget, and decisions.", type: "business", sections: [{ title: "Goal" }, { title: "Workstreams" }, { title: "People" }, { title: "Budget" }, { title: "Decisions" }], fields: [] },
    { id: "template-restaurant", name: "Restaurant Event", description: "Venue-ready event structure.", type: "restaurant_event", sections: [{ title: "Concept" }, { title: "Venue" }, { title: "Vendors" }, { title: "Promotion" }, { title: "Operations" }, { title: "Needs Jerry" }], fields: [{ label: "Capacity", type: "number" }, { label: "Ticket Price", type: "currency" }] },
    { id: "template-party", name: "Party", description: "Guest experience, food, music, setup, and what worked.", type: "party", sections: [{ title: "Guest List" }, { title: "Food" }, { title: "Music" }, { title: "Setup" }, { title: "What Worked" }], fields: [] },
  ],
  orders: [],
};
