import type { AppState, Thing, ThingSection } from "./domain";

const date = (day: string) => `2026-${day}T15:00:00-05:00`;

type SeedThing = Omit<Thing, "items" | "customFields" | "sections"> & {
  sections: Array<Omit<ThingSection, "position">>;
};

const baseThings: SeedThing[] = [
  {
    id: "camping-red-oak",
    title: "Camping — Red Oak",
    summary: "A comfortable, elevated campsite for 15 people—with room for a cot, projector, and lighting that feels intentional.",
    ownerNextAction: "Jerry needs to approve the CORE tent purchase plan.",
    assistantNextAction: "Compare two quieter campsite lighting directions.",
    category: "Trips & Experiences",
    status: "Moving",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: true,
    archived: false,
    lastMoved: date("08-13"),
    location: "Red Oak, Illinois",
    dates: [
      { label: "Camping weekend", start: date("09-04"), end: date("09-07"), precision: "range", readiness: "Tent undecided · six open preparations", unresolved: 6 },
      { label: "Demo Yeti return window", start: date("09-14"), precision: "exact", readiness: "Demo data — confirm keep or return; no real order", unresolved: 1 },
    ],
    contacts: [{ id: "jordan", name: "Jordan", context: "Camping friend" }],
    options: [
      { id: "core-tent", name: "CORE 10-person cabin tent", description: "Tall cabin shape with room for the cot and projector setup.", price: "$349.99", source: "https://www.coreequipment.com/", recommendation: "Best fit for the group layout and easiest setup.", tradeoff: "Bulkier packed size than the alternatives.", status: "recommended" },
      { id: "snow-peak-chair", name: "Snow Peak Low Beach Chair", description: "Low-profile canvas chair with wood arms.", price: "$169", source: "https://www.snowpeak.com/", recommendation: "Cleanest look around the fire.", tradeoff: "Premium price for a camp chair.", status: "saved" },
      { id: "dji-power", name: "DJI Power 1000 V2", description: "Quiet portable power for the projector and campsite lighting.", source: "https://www.dji.com/", tradeoff: "Confirm actual power needs before buying.", status: "considering" },
    ],
    notes: [{ id: "camp-note-1", author: "Jerry", body: "Keep the setup intentional, not corny.", at: date("08-12") }],
    links: [],
    followUps: [],
    sections: [
      { id: "camp-tent", title: "Tent Setup", body: "CORE tent, cot, rug, lighting, bedside table, and shoe storage." },
      { id: "camp-food", title: "Food", body: "Plan simple meals and cooler setup for fifteen people." },
      { id: "camp-entertainment", title: "Entertainment", body: "Projector and screen are already owned." },
      { id: "camp-hiking", title: "Hiking", body: "Choose one group-friendly trail." },
      { id: "camp-power", title: "Power", body: "Confirm the projector and lighting load before buying a battery." },
      { id: "camp-packing", title: "Packing", body: "Keep a shared, editable packing list." },
    ],
  },
  {
    id: "oasis-paint-sip",
    title: "Mamma Mia — Dancing Queen",
    summary: "An ABBA-inspired night at Oasis Kitchen & Bar. The concept is set; instructor and supplies need final approval.",
    ownerNextAction: "Approve Vanessa for Sep 12 at $200.",
    assistantNextAction: "Prepare the supply plan after Jerry decides on Vanessa.",
    category: "Business",
    status: "Moving",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-13"),
    waitingOn: "Jerry",
    location: "Oasis Kitchen & Bar · Lockport",
    dates: [{ label: "Paint & Sip", start: date("09-12"), precision: "exact", readiness: "Instructor awaiting approval", unresolved: 2 }],
    contacts: [
      { id: "vanessa", name: "Vanessa", context: "Painter / instructor", location: "Chicago", note: "Quoted $200; available for Sep 12." },
      { id: "adrian", name: "Adrian", context: "Venue owner", organization: "Oasis Kitchen & Bar", location: "Lockport" },
    ],
    options: [],
    notes: [],
    links: [],
    followUps: [{ id: "followup-adrian", waitingOn: "Adrian", date: date("08-15"), channel: "Draft message", note: "Confirm venue capacity before promotion begins.", state: "drafted" }],
    sections: [
      { id: "oasis-concept", title: "Concept", body: "Dancing Queen: an ABBA-inspired social painting night with warm lighting, a guided piece, and a short after-paint playlist." },
      { id: "oasis-vendors", title: "Vendors", body: "Vanessa is the leading instructor at a quoted $200." },
      { id: "oasis-promotion", title: "Promotion", body: "Draft an ABBA-inspired visual and venue announcement. Nothing has been posted." },
      { id: "oasis-budget", title: "Budget", body: "Working capacity: 60 · ticket direction: $40 · venue and supply costs remain unconfirmed." },
      { id: "oasis-operations", title: "Operations", body: "Confirm materials, room layout, timing, and check-in." },
      { id: "oasis-adrian", title: "Needs Adrian", body: "Confirm venue capacity and operational constraints." },
      { id: "oasis-jerry", title: "Needs Jerry", body: "Approve Vanessa and the initial event direction." },
    ],
  },
  {
    id: "christmas-trip",
    title: "Family Christmas Trip 2026",
    summary: "A family holiday somewhere warm or culturally rich. Italy, Spain, and Costa Rica are the current shortlist.",
    ownerNextAction: "Review the destination shortlist and choose the trip energy.",
    assistantNextAction: "Compare flight windows for Italy and Costa Rica.",
    category: "Trips & Experiences",
    status: "Exploring",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-05"),
    dates: [{ label: "Possible family trip", start: "2026-12-01T12:00:00-06:00", precision: "month", readiness: "Destination shortlist in progress", unresolved: 4 }],
    contacts: [],
    options: [
      { id: "italy", name: "Italy", description: "Food, cities, and family-friendly rail travel.", recommendation: "Best all-around memory maker.", tradeoff: "Cooler weather and higher holiday pricing.", status: "recommended" },
      { id: "spain", name: "Spain", description: "Milder cities, great food, and strong value.", tradeoff: "Still a long travel day.", status: "considering" },
      { id: "costa-rica", name: "Costa Rica", description: "Warm weather, nature, and simpler outdoor days.", tradeoff: "Less city/culture than Europe.", status: "considering" },
    ],
    notes: [],
    links: [],
    followUps: [],
    sections: [{ id: "trip-question", title: "Decision to make", body: "Do we want warmth and ease, or a bigger cultural trip? Once that is clear, flight windows and neighborhoods can be compared." }],
  },
  {
    id: "fall-wardrobe",
    title: "Fall Wardrobe",
    summary: "Find better trousers and a few clean fall pieces—good fabric, quiet color, no loud logos or generic-looking products.",
    ownerNextAction: "Review Maria’s first trouser recommendation.",
    assistantNextAction: "Find two quieter trouser options with a clean drape.",
    category: "Shopping",
    status: "Exploring",
    permission: "APPROVE",
    keepMoving: true,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-11"),
    dates: [],
    contacts: [],
    options: [
      { id: "suitsupply", name: "SuitSupply wool trousers", description: "Clean drape, useful neutral, easy to dress up or down.", recommendation: "Best place to start.", tradeoff: "Needs an in-person fit check.", status: "recommended" },
      { id: "dark-denim", name: "Clean dark denim", description: "No distressing or loud hardware.", status: "saved" },
      { id: "olive-trouser", name: "Relaxed olive trouser", description: "More fashion-forward cut.", tradeoff: "Rejected as too loud.", status: "rejected" },
    ],
    notes: [],
    links: [],
    followUps: [],
    sections: [{ id: "wardrobe-fit", title: "Taste brief", body: "Simple silhouette, strong fabric, earthy or dark neutrals, minimal branding." }],
  },
  {
    id: "birthday",
    title: "Birthday",
    summary: "Plan something memorable without forcing a big production. The direction is still open.",
    ownerNextAction: "Choose: intimate dinner, one-night escape, or group night.",
    assistantNextAction: "Wait for Jerry’s direction before researching venues.",
    category: "Personal",
    status: "Needs You",
    permission: "YOU",
    keepMoving: false,
    surpriseMe: false,
    archived: false,
    lastMoved: date("08-09"),
    waitingOn: "Jerry",
    dates: [{ label: "Birthday", start: date("09-08"), precision: "exact", readiness: "No plan selected yet", unresolved: 3 }],
    contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "birthday-direction", title: "Smallest decision", body: "Choose the energy: intimate dinner, one-night escape, or a bigger group night." }],
  },
  {
    id: "dj-restart",
    title: "DJ Restart",
    summary: "Explore a low-pressure way to start making and sharing music again.",
    ownerNextAction: "Choose three records for a private 20-minute set.",
    assistantNextAction: "Surface one low-pressure setup idea when the timing feels right.",
    category: "Creative",
    status: "Someday",
    permission: "YOU",
    keepMoving: true,
    surpriseMe: true,
    archived: false,
    lastMoved: date("07-28"),
    dates: [], contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "dj-next", title: "A low-pressure next move", body: "Build one 20-minute set around three records you already love—nothing to publish yet." }],
  },
  {
    id: "chicago-date-nights",
    title: "Chicago Date Nights",
    summary: "Keep an eye out for interesting, non-generic date-night ideas around Chicago.",
    ownerNextAction: "Save or reject the next idea Maria surfaces.",
    assistantNextAction: "Find one design-forward Chicago date idea under $200.",
    category: "Future",
    status: "Someday",
    permission: "GO",
    keepMoving: false,
    surpriseMe: true,
    archived: false,
    lastMoved: date("08-01"),
    location: "Chicago",
    dates: [], contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "date-taste", title: "What fits", body: "Good design, food or music with a point of view, and enough room to actually talk." }],
  },
  {
    id: "summer-house-party",
    title: "Summer House Party",
    summary: "A finished backyard evening with a vinyl set, low lighting, and family-style food.",
    ownerNextAction: "No next move — this memory is complete.",
    assistantNextAction: "No next move — this memory is complete.",
    category: "Personal",
    status: "Done",
    permission: "GO",
    keepMoving: false,
    surpriseMe: false,
    archived: true,
    lastMoved: date("07-18"),
    dates: [], contacts: [], options: [], notes: [], links: [], followUps: [],
    sections: [{ id: "party-memory", title: "What worked", body: "The smaller guest list and family-style table made the night feel easy. Keep that format." }],
  },
];

export const seedThings: Thing[] = baseThings.map((thing) => ({
  ...thing,
  owner: thing.owner ?? "Jerry",
  priority: thing.priority ?? "normal",
  tags: thing.tags ?? [],
  relatedThingIds: thing.relatedThingIds ?? [],
  collaborators: thing.collaborators ?? ["Maria"],
  sections: thing.sections.map((section, position) => ({ ...section, position })),
  items: thing.id === "camping-red-oak" ? [
    ["CORE 10-person cabin tent", "product"], ["cot", "checklist"], ["tasteful campsite lighting", "idea"], ["compact bedside table", "product"], ["shoe rack / outdoor folding table", "product"], ["tent rug", "product"],
  ].map(([title, type], position) => ({ id: `camp-item-${position + 1}`, sectionId: "camp-tent", title, type: type as Thing["items"][number]["type"], status: "open", position })) : [],
  customFields: (thing.id === "oasis-paint-sip" ? [
    { id: "oasis-capacity", key: "capacity", label: "Capacity", type: "number", value: 60, position: 0 },
    { id: "oasis-ticket", key: "ticket_price", label: "Ticket Price", type: "currency", value: 40, position: 1 },
    { id: "oasis-instructor", key: "instructor", label: "Instructor", type: "contact", value: "Vanessa", position: 2 },
    { id: "oasis-venue", key: "venue", label: "Venue", type: "short_text", value: "Oasis Kitchen & Bar", position: 3 },
  ] : []) as Thing["customFields"],
})).concat({
  id: "camping-tent-setup", title: "Tent Setup", subtitle: "Subthing of Camping — Red Oak", description: "The physical sleep and shelter setup, separated so it can move independently.", summary: "Build a comfortable, intentional tent interior around the CORE cabin tent.", ownerNextAction: "Approve the main tent plan.", assistantNextAction: "Turn the selected gear into a setup checklist.", category: "Trips & Experiences", status: "Moving", permission: "APPROVE", keepMoving: true, surpriseMe: false, archived: false, lastMoved: date("08-13"), owner: "Jerry", collaborators: ["Maria"], priority: "high", tags: ["camping", "setup"], parentId: "camping-red-oak", relatedThingIds: [], dates: [], contacts: [], options: [], notes: [], links: [], followUps: [], sections: [{ id: "tent-layout", title: "Layout", body: "Cot, bedside table, shoe storage, rug, and clear walking space.", position: 0 }, { id: "tent-lighting", title: "Lighting", body: "Warm, low-output lighting inside and around the entrance.", position: 1 }], items: [], customFields: [],
});

export const initialState: AppState = {
  schemaVersion: 3,
  revision: 1,
  things: seedThings,
  approvals: [
    { id: "approve-vanessa", thingId: "oasis-paint-sip", title: "Approve Vanessa for the Paint & Sip", context: "Vanessa can lead the event for $200 and is available Sep 12.", recommendation: "Approve her—she has the right group experience and fits the budget.", whyNow: "The event is one month out and supplies depend on the instructor plan.", actionLabel: "Approve $200", meta: "$200 · Sep 12 · Vanessa", status: "pending" },
    { id: "approve-tent", thingId: "camping-red-oak", title: "Camping chair", context: "Approve Snow Peak Low Beach Chair for $169?", recommendation: "Best balance of comfort and clean design. Kermit Chair looks stronger but is nearly twice the cost.", whyNow: "The campsite layout and packing list depend on the chair direction.", actionLabel: "Approve $169", meta: "$169 · Purchase not placed", status: "pending", amount: 169, currency: "USD", urgency: "normal", options: [{ id: "chair-approve", label: "Approve Snow Peak", description: "Best balance of comfort and clean design." }, { id: "chair-keep-looking", label: "Keep looking" }, { id: "chair-save", label: "Save for later" }], responses: [] },
    { id: "approve-trip", thingId: "christmas-trip", title: "Review the destination shortlist", context: "Italy, Spain, and Costa Rica are the three strongest directions.", recommendation: "Start with Italy; keep Costa Rica as the warmer backup.", whyNow: "Holiday flight windows are worth narrowing before prices tighten.", actionLabel: "Review shortlist", meta: "3 destinations · December 2026", status: "pending" },
    { id: "approve-birthday", thingId: "birthday", title: "Choose the birthday energy", context: "The useful decision is intimate dinner, one-night escape, or bigger group night.", recommendation: "Pick the feeling first; planning can stay light after that.", whyNow: "A direction unlocks every other detail.", actionLabel: "Choose direction", meta: "Owner-only · Sep 8", status: "pending" },
  ],
  activities: [
    { id: "activity-1", thingId: "camping-red-oak", actor: "Maria", text: "Maria compared the CORE 10-person tent with two alternatives.", at: date("08-13") },
    { id: "activity-2", thingId: "oasis-paint-sip", actor: "Maria", text: "Vanessa confirmed availability for Sep 12.", at: date("08-13") },
    { id: "activity-3", thingId: "fall-wardrobe", actor: "Maria", text: "Maria narrowed the trouser search to three quieter options.", at: date("08-12") },
    { id: "activity-4", thingId: "camping-red-oak", actor: "Jerry", text: "Jerry saved the Snow Peak chair for later.", at: date("08-12") },
    { id: "activity-5", thingId: "oasis-paint-sip", actor: "Maria", text: "Maria drafted a follow-up for Adrian.", at: date("08-11") },
  ],
  inbox: [
    { id: "inbox-1", type: "voice", raw: "For camping maybe we need tasteful lights around the tent, something inside, and a small table next to the cot. I don’t want it looking corny.", status: "needs_review", createdAt: date("08-13"), proposal: { title: "Camping — Red Oak", summary: "Explore exterior and interior lighting plus a small cot-side table; keep the campsite tasteful.", category: "Trips & Experiences", status: "Moving", permission: "GO", relatedThingId: "camping-red-oak", extracted: ["Exterior ambient lighting", "Interior tent lighting", "Small cot-side table", "Constraint: intentional, not corny"], confidence: "High confidence" } },
    { id: "inbox-2", type: "link", raw: "https://example.com/wisconsin-cabin — might be fire for fall. Look into it whenever.", status: "needs_review", createdAt: date("08-12"), proposal: { title: "Wisconsin Cabin Weekend", summary: "Look into a possible cabin weekend in Wisconsin this fall.", category: "Trips & Experiences", status: "Someday", permission: "GO", extracted: ["Location: Wisconsin", "Timing: fall, date uncertain", "Intent: explore a cabin weekend"], confidence: "Please check" } },
  ],
  contacts: [
    { id: "vanessa", name: "Vanessa", context: "Artist / Painting Instructor", organization: "Independent", location: "Chicago", note: "Art degree · teaches kids · quoted $200", tags: ["vendor", "artist"] },
    { id: "adrian", name: "Adrian", context: "Owner", organization: "Oasis Kitchen & Bar", location: "Lockport", tags: ["venue", "restaurant"] },
    { id: "jordan", name: "Jordan", context: "Camping friend", tags: ["friend", "camping"] },
  ],
  preferences: [
    { id: "pref-camp-aesthetic", domain: "camping gear", attribute: "aesthetic", statement: "Avoid cheap or corny campsite styling.", sentiment: "dislikes", sourceType: "confirmed note", sourceId: "camp-note-1", confidence: 1, confirmed: true, createdAt: date("08-12") },
  ],
  templates: [
    { id: "template-blank", name: "Blank", description: "Start with an open brief.", type: "blank", sections: [], fields: [] },
    { id: "template-trip", name: "Trip", description: "Destinations, travel, stays, people, and budget.", type: "trip", sections: [{ title: "Destinations" }, { title: "Travel" }, { title: "Stays" }, { title: "People" }, { title: "Budget" }, { title: "Need Decision" }], fields: [{ label: "Budget", type: "currency" }, { label: "Travelers", type: "number" }] },
    { id: "template-event", name: "Event", description: "Concept, vendors, promotion, budget, and operations.", type: "event", sections: [{ title: "Concept" }, { title: "Vendors" }, { title: "Promotion" }, { title: "Budget" }, { title: "Operations" }], fields: [{ label: "Capacity", type: "number" }, { label: "Ticket Price", type: "currency" }] },
    { id: "template-shopping", name: "Shopping Project", description: "Research, shortlist, saved, bought, and rejected.", type: "shopping", sections: [{ title: "Research" }, { title: "Shortlist" }, { title: "Saved" }, { title: "Bought" }, { title: "Rejected" }], fields: [{ label: "Budget", type: "currency" }] },
    { id: "template-personal", name: "Personal Admin", description: "Context, next actions, documents, and follow-up.", type: "personal_admin", sections: [{ title: "Context" }, { title: "Next Actions" }, { title: "Documents" }, { title: "Follow-up" }], fields: [] },
    { id: "template-business", name: "Business Initiative", description: "Goals, workstreams, people, budget, and decisions.", type: "business", sections: [{ title: "Goal" }, { title: "Workstreams" }, { title: "People" }, { title: "Budget" }, { title: "Decisions" }], fields: [] },
    { id: "template-restaurant", name: "Restaurant Event", description: "Venue-ready event structure.", type: "restaurant_event", sections: [{ title: "Concept" }, { title: "Venue" }, { title: "Vendors" }, { title: "Promotion" }, { title: "Operations" }, { title: "Needs Jerry" }], fields: [{ label: "Capacity", type: "number" }, { label: "Ticket Price", type: "currency" }] },
    { id: "template-party", name: "Party", description: "Guest experience, food, music, setup, and what worked.", type: "party", sections: [{ title: "Guest List" }, { title: "Food" }, { title: "Music" }, { title: "Setup" }, { title: "What Worked" }], fields: [] },
  ],
  orders: [],
};
