"use client";

import { useRef, useState } from "react";
import { Check, File, Image as ImageIcon, Link2, Mic, Paperclip, Plus, Send, Type, X } from "lucide-react";
import { useApp } from "@/components/app-provider";
import { captureSchema, type InboxItem } from "@/lib/domain";
import { formatDate } from "@/lib/format";

const captureTypes = [{ value: "text", label: "Type", icon: Type }, { value: "voice", label: "Voice", icon: Mic }, { value: "photo", label: "Photo", icon: ImageIcon }, { value: "link", label: "Link", icon: Link2 }, { value: "file", label: "File", icon: File }] as const;

export default function InboxPage() {
  const { inbox, things, capture, acceptProposal, dismissInbox, reopenInbox } = useApp();
  const [type, setType] = useState<InboxItem["type"]>("text"); const [text, setText] = useState(""); const [fileName, setFileName] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const fileInput = useRef<HTMLInputElement>(null);

  async function submit(event: React.FormEvent) { event.preventDefault(); const raw = text || (fileName ? `${type === "voice" ? "Voice note" : type === "photo" ? "Photo" : "File"}: ${fileName}` : ""); const parsed = captureSchema.safeParse({ text: raw, type }); if (!parsed.success) return setError(parsed.error.issues[0]?.message ?? "Add a thought first."); const result = await capture(raw, type, fileName || undefined); if (!result.ok) return setError(result.message); setText(""); setFileName(""); setError(""); setNotice(result.message); }
  const reviews = inbox.filter((item) => item.status === "needs_review"); const recent = inbox.filter((item) => item.status !== "needs_review" && item.status !== "failed").slice(0, 10);

  return <div className="page calm-inbox-page"><header className="calm-page-header"><h1>Inbox</h1></header>
    <form className="capture-composer calm-capture" onSubmit={submit}><h2>What’s on your mind?</h2><textarea aria-label="What are you thinking about?" placeholder={type === "link" ? "Paste a link and add what caught your eye…" : type === "voice" ? "Upload audio, or type the thought…" : "A trip, something to buy, someone to follow up with…"} value={text} onChange={(event) => setText(event.target.value)} />{fileName ? <div className="attachment-chip"><Paperclip size={14} /><span>{fileName}</span><button type="button" onClick={() => setFileName("")} aria-label="Remove attachment"><X size={14} /></button></div> : null}<input ref={fileInput} className="sr-only" type="file" aria-label="Upload private attachment" accept={type === "photo" ? "image/*" : type === "voice" ? "audio/*" : undefined} onChange={(event) => setFileName(event.target.files?.[0]?.name ?? "")} /><div className="capture-bottom"><div className="capture-types" role="group" aria-label="Capture type">{captureTypes.map(({ value, label, icon: Icon }) => <button type="button" key={value} className={type === value ? "active" : ""} onClick={() => { setType(value); setError(""); if (["photo", "file", "voice"].includes(value)) setTimeout(() => fileInput.current?.click(), 0); }}><Icon size={16} /><span>{label}</span></button>)}</div><button className="button primary" type="submit"><Send size={15} />Save</button></div>{error ? <p className="form-error" role="alert">{error}</p> : null}{notice ? <p className="calm-capture-result" role="status"><Check size={15} />{notice}</p> : null}</form>

    {reviews.length ? <section className="inbox-section calm-review"><h2>Needs review</h2><div>{reviews.map((item) => { const suggestions = things.filter((thing) => !thing.archived && thing.category === item.proposal?.category).slice(0, 3); return <article key={item.id}><p>{item.raw}</p><small>{formatDate(item.createdAt)}</small><h3>Where should this go?</h3><div className="filing-choices">{suggestions.map((thing) => <button key={thing.id} onClick={async () => setNotice((await acceptProposal(item.id, "attach", undefined, "idea", thing.id)).message)}>{thing.title}</button>)}<button className="button primary" onClick={async () => setNotice((await acceptProposal(item.id, "create")).message)}><Plus size={13} />New Thing</button><button className="quiet-text" onClick={async () => setNotice((await dismissInbox(item.id)).message)}>Dismiss</button></div></article>; })}</div></section> : null}

    <section className="inbox-section recent-captures"><h2>Recent captures</h2><div>{recent.map((item) => { const target = things.find((thing) => thing.id === item.proposal?.relatedThingId); const section = target?.sections.find((entry) => entry.title.toLowerCase().includes("tent")); return <article key={item.id}><div><p>{item.raw}</p><small>{target ? `Added to ${target.title}${section ? ` → ${section.title}` : ""}` : item.status === "accepted" ? `Created ${item.proposal?.title ?? "a Thing"}` : "Saved"} · {formatDate(item.createdAt)}</small></div>{item.status === "attached" ? <button onClick={async () => setNotice((await reopenInbox(item.id)).message)}>Undo</button> : null}</article>; })}</div></section>
  </div>;
}
